export const BarcodeIcon = (props: { className?: string }) => (
  <svg
    viewBox="0 0 80 40"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <rect
      width="5"
      height="100%"
      fill="white"
    />
    <rect
      width="3"
      height="100%"
      x="9"
      fill="white"
    />
    <rect
      width="10"
      height="100%"
      x="14"
      fill="white"
    />
    <rect
      width="3"
      height="100%"
      x="34"
      fill="white"
    />
    <rect
      width="5"
      height="100%"
      x="40"
      fill="white"
    />
    <rect
      width="10"
      height="100%"
      x="50"
      fill="white"
    />
    <rect
      width="3"
      height="100%"
      x="70"
      fill="white"
    />
    <rect
      width="3"
      height="100%"
      x="75"
      fill="white"
    />
  </svg>
);
